### ISSUE TITLE
This issue can be fixed in the config file no need to update

### ISSUE THREAD

**Issue by hellsmadness** [Tymmey/Playable-Templar#1]
new one is still currently the same fire value prior on first release but everything else is fixed from what I'm seeing

**Comment by hellsmadness** [comment]
Did a test again with the current one and it is having an issue with 1.0.2 the firing rate is still the same as 1.0.0 and 1.0.1 I looked over the coding and it seemed to be fixed I can't find the issue why it's not normal

**Comment by Tymmey** [comment]
remove config file once ;)

**Comment by hellsmadness** [comment]
Done thanks
