### ISSUE TITLE
Attack Speed from Shift not decreasing with primary skill

### ISSUE THREAD

**Issue by RodrigoZXMota** [Tymmey/Playable-Templar#2]
Primary minigun will keep the buff even when it wears off, making it incredibly powerful without items or levels

**Comment by Tymmey** [comment]
i think this was always like this :D, i'll take a look into it though.

**Comment by Tymmey** [comment]
ok, so i checked this further. basically there is a starting fire rate and a maximum firerate. i think the maximum firerate can not go further after a specific point. so what the overdrive buff does is, that it's making you get to this point just more quickly. after the buff goes away, you still fire with a high fire rate, but you would have gotten to this point without the buff as well. just only a little bit later.
