### ISSUE TITLE
Camera not centered while playing templar

### ISSUE THREAD

**Issue by Vixdew** [Tymmey/Playable-Templar#3]
This is a little hard to explain. With other characters, if you spin the camera around, it will keep its position relative to the character, but with the templar it'll spin around him in such a way that the camera is sometimes to the left of the templar and sometimes to the right, depending on the direction you are facing relative to the rest of the map.

**Comment by Tymmey** [comment]
yeah. i'm still at this. but basically i have the same camera settings as before. but centering it on the gun is a little bit hard.
