### ISSUE TITLE
Yo I love this mod my mom  died of ligma please update 

### ISSUE THREAD

**Issue by ghost** [Tymmey/Playable-Templar#5]
Eyo your mod is sick and so is my mom. Please update or else i'm gonna bring back bill gates. ( this is just a small request to please update cus templar doesn't show up love the mod !)

**Comment by Tymmey** [comment]
Yeah, thanks for this... but currently templar is pretty far down on my list..
currently fixed my lemurian which had priority..
now comes Elden Ring, Work and after this ... .Lost Ark.

If i get bored I may look into it though..,, but can't give any promises..

**Comment by Tymmey** [comment]
you may be lucky :P

**Comment by ghost** [comment]
My MAN ITS FIXED ♡. GIVE ME YOUR PAYPAL I dono.  Though the characters
alternate special is a little bugged it makes you have huntress special.

**Comment by Tymmey** [comment]
yeah you're welcome, and thanks ! :D but no need to dono, i like to play templar as well.

what you mean with special is bugged? 
basically i just did the porting though

**Comment by ghost** [comment]
In multi-player, all alternative abilities become huntress ballista. You
can have all 4 of your abilities just be huntress. The armor buff when
shooting and regen on tar overdrive don't seem to work. Only in
multi-player I'm not sure why
