### ISSUE TITLE
Tar Overdrive Broken

### ISSUE THREAD

**Issue by LightWolfIllumi** [Tymmey/Playable-Templar#7]
I've noticed that the Tar Overdrive ability is broken currently as it stands. It will either not give the bonuses at and just cover you in Tar, or it will just give the healing to you but it's VERY delayed to the point medkit is better. I don't know when it broke since I took a 2 month break from modded RoR2 but I can tell this ability is not working properly.

**Comment by Tymmey** [comment]
Sorry bro, but I'm no longer doing anything for the templar :(
